#NeyUPCrystalDamage (Увеличение урона от кристала энда)

end_crystal_damage_multiplier: 4.0 #указывать в процентах (default - 4 > 400%)
  
drop-exp: true #Будет ли падать уровень при уроне от кристала (Расчитывается в зависимости от урона)