#_   _            _   _ ____   ____                _        _ ____
#| \ | | ___ _   _| | | |  _ \ / ___|_ __ _   _ ___| |_ __ _| |  _ \  __ _ _ __ ___   __ _  __ _  ___
#|  \| |/ _ \ | | | | | | |_) | |   | '__| | | / __| __/ _` | | | | |/ _` | '_ ` _ \ / _` |/ _` |/ _ \
#| |\  |  __/ |_| | |_| |  __/| |___| |  | |_| \__ \ || (_| | | |_| | (_| | | | | | | (_| | (_| |  __/
#|_| \_|\___|\__, |\___/|_|    \____|_|   \__, |___/\__\__,_|_|____/ \__,_|_| |_| |_|\__,_|\__, |\___|
#|___/                        |___/                                            |___/

#Разработчик - https://vk.com/k_gra4ev.
#Специально для spigotmc.ru

Settings:
  multiplier: 4.0 #указывать в процентах (default - 4 > 400%)
  drop-exp: false #Будет ли падать уровень при уроне от кристала (Расчитывается в зависимости от урона)

Messages: #Сообщения поддерживают HEX
  message-before-damage:
    enabled: true
    text:
      - ""
      - " &#5dff52[⛄] &fБум! В следующий раз будьте осторожнее! "
      - ""