# _   _            _   _ ____   ____                _        _ ____
#| \ | | ___ _   _| | | |  _ \ / ___|_ __ _   _ ___| |_ __ _| |  _ \  __ _ _ __ ___   __ _  __ _  ___
#|  \| |/ _ \ | | | | | | |_) | |   | '__| | | / __| __/ _` | | | | |/ _` | '_ ` _ \ / _` |/ _` |/ _ \
#| |\  |  __/ |_| | |_| |  __/| |___| |  | |_| \__ \ || (_| | | |_| | (_| | | | | | | (_| | (_| |  __/
#|_| \_|\___|\__, |\___/|_|    \____|_|   \__, |___/\__\__,_|_|____/ \__,_|_| |_| |_|\__,_|\__, |\___|
#            |___/                        |___/                                            |___/

#Разработчик - https://t.me/NeyOff
#Специально для spigotmc

settings:

  # Множитель урона (1.0 = 100%, 4.0 = 400%)
  multiplier: 0.1

permissions:
  enabled: false
  bypass-permission: "crystal.damage.bypass"

messages:
  message-before-damage:
    # Включить сообщение
    enabled: true
    # Текст с цветами (&a) и HEX (#FF0000)
    text:
      - ""
      - " #5dff52[⛄] &fБум! В следующий раз будьте осторожнее! "
      - ""